name: 'Deploy to review env'
on: create

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  debug:
    name: dump event info
    runs-on: ubuntu-latest
    steps:
      - name: dump event info
        env:
          EVENT: "${{ toJSON(github.event) }}"
        run: echo ${EVENT} | jq '.';
  deploy:
    name: 'Deploy to review env'
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type }} == "branch" and ${{ startsWith(github.event.ref, 'feature-') }}

    steps:
      - name: checkout flux repo
        uses: actions/checkout@v2
        with:
          repository: haisumb/aks-gitops-mvp-flux
          token: ${{ secrets.GITHUB_PAT }}
      - name: install jinja2 cli
        run: |
           pip3 install -U pip setuptools;
           pip3 install jinja2-cli pyyaml;
      - name: delete and re-create folder
        run: |
          rm -rf environments/staging/centralus/apps/${{ github.event.ref }} || true;
          mkdir -p environments/staging/centralus/apps/${{ github.event.ref }};
      - name: generate values file
        run: |
          cat <<EOF > ${{ runner.temp }}/values.yaml
          automated: "true"
          namespace: ${{ github.event.ref }}
          branch: ${{ github.event.ref }}
          app:
            name: helloworld
            host: ${{ github.event.ref }}.helloworld.com
          chart:
            repo: git@github.com:haisumb/aks-gitops-mvp-flux
            path: environments/staging/centralus/charts/generic
            ref: master
          image:
            repo: haisumb/helloworld
            tag: ${{ github.event.ref }}-${GITHUB_SHA}
          canary:
            enabled: "true"
            bluegreen:
              enabled: "false"
            promotion:
              enabled: "false"
              status: approve
          EOF
      - name: generate helm release file
        env:
          TEMPLATE: environments/staging/centralus/templates/helmrelease.j2
          OUTPUT_FILE: environments/staging/centralus/apps/${{github.event.ref}}/helloworld.yaml
          VAR_FILE: ${{ runner.temp }}/values.yaml
        run:
          /home/runner/.local/bin/./jinja2 "${TEMPLATE}" "${VAR_FILE}" --format=yaml > "${OUTPUT_FILE}";
          cat "${OUTPUT_FILE}";
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add environments/staging/centralus/apps/${{github.event.ref}}
          git commit -m "Add release file for ${{ github.event.ref }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_PAT }}
          repository: haisumb/aks-gitops-mvp-flux