name: 'Build application'
on:
  push:
    branches:
      - '*'
      - '!master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: 'Publish Image'
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: 'Checkout'
        if: github.event_name == 'push'
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Docker Registry login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Building Docker Image
        env:
          DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
          CONTAINER_NAME: helloworld
        run: |
          docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:${{steps.extract_branch.outputs.branch}}-${GITHUB_SHA} .
      - name: Push Docker Container to Registry
        env:
          DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
          CONTAINER_NAME: helloworld
        run: |
           docker push $DOCKER_USERNAME/$CONTAINER_NAME:${{steps.extract_branch.outputs.branch}}-${GITHUB_SHA}
  test:
    name: 'Test App'
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Docker Registry login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Run container
        env:
          DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
          CONTAINER_NAME: helloworld
        run: |
          docker run -d -p 9898:9898 $DOCKER_USERNAME/$CONTAINER_NAME:${{steps.extract_branch.outputs.branch}}-${GITHUB_SHA}
      - name: Run curl to test home
        run: |
          sleep 2s;
          curl -v -f http://localhost:9898;
      - name: Run curl to test metrics
        run: |
          sleep 2s;
          curl -v -f http://localhost:9898/metrics;
