name: 'Publish Docker Image'
on: push
jobs:
  publish:
    name: 'Publish Image'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Building Docker Image
        env:
          DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
          CONTAINER_NAME: helloworld
        run:
          docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:latest .
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M:%S')"
      - name: Push Docker Container to Registry
        env:
          DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
          CONTAINER_NAME: helloworld
        run: 
          docker push $DOCKER_USERNAME/$CONTAINER_NAME:${{github.ref}}-${{steps.date.outputs.date}}-${{ github.sha }}