name: 'Deploy feature to prod'
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: 'Deploy feature to prod'
    runs-on: ubuntu-latest

    steps:
      - name: checkout flux repo
        uses: actions/checkout@v2
        with:
          repository: haisumb/aks-gitops-mvp-flux
          token: ${{ secrets.GITHUB_PAT }}
      - name: install jinja2 cli
        run: |
           pip3 install -U pip setuptools;
           pip3 install jinja2-cli pyyaml;
      - name: create folder
        run: |
          mkdir -p environments/staging/centralus/apps/default;
      - name: generate values file
        run: |
          cat <<EOF > ${{ runner.temp }}/values.yaml
          automated: "true"
          namespace: default
          branch: ${{ github.event.pull_request.head.ref }}
          app:
            name: helloworld-${{ github.event.pull_request.head.ref }}
            host: ${{ github.event.pull_request.head.ref }}.prod.helloworld.com
          chart:
            repo: git@github.com:haisumb/aks-gitops-mvp-flux
            path: environments/staging/centralus/charts/generic
            ref: master
          image:
            repo: haisumb/helloworld
            tag: ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}
          canary:
            enabled: "false"
            bluegreen:
              enabled: "true"
            promotion:
              enabled: "false"
              status: approve
          EOF
      - name: generate helm release file
        env:
          TEMPLATE: environments/staging/centralus/templates/helmrelease.j2
          OUTPUT_FILE: environments/staging/centralus/apps/default/helloworld-${{ github.event.pull_request.head.ref }}.yaml
          VAR_FILE: ${{ runner.temp }}/values.yaml
        run:
          /home/runner/.local/bin/./jinja2 "${TEMPLATE}" "${VAR_FILE}" --format=yaml > "${OUTPUT_FILE}";
          cat "${OUTPUT_FILE}";
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add environments/staging/centralus/apps/default
          git commit -m "Add release file for ${{ github.event.pull_request.head.ref }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_PAT }}
          repository: haisumb/aks-gitops-mvp-flux
 